package pluginSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class AddOns_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "pluginSolution.plugin.AddOns_ActionGroup";

  public AddOns_ActionGroup(@Nullable ApplicationPlugin plugin) {
    super("AddOns", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    AddOns_ActionGroup.this.addAction("pluginSolution.plugin.GenerateService_Action");
    AddOns_ActionGroup.this.addAction("pluginSolution.plugin.ReInitializeService_Action");
    AddOns_ActionGroup.this.addAction("pluginSolution.plugin.GenerateModel_Action");
  }
}
