package pluginSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;
import com.intellij.openapi.actionSystem.Shortcut;
import com.intellij.openapi.actionSystem.KeyboardShortcut;
import javax.swing.KeyStroke;

public class MacOSX_KeymapChanges extends BaseKeymapChanges {
  public MacOSX_KeymapChanges() {
    // simple 
    // simple with remove/replace 
    addSimpleShortcut("pluginSolution.plugin.GenerateService_Action", new BaseKeymapChanges.ShortcutWrapper(getShortcut("ctrl R"), false, true));
    // simple parameterized 
    // complex 
  }
  public String getScheme() {
    return "Mac OS X";
  }
  public static Shortcut getShortcut(String stroke) {
    return new KeyboardShortcut(KeyStroke.getKeyStroke(stroke), null);
  }
}
