package MetaModel.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Multiplicity extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Multiplicity() {
    super(0x9859e7a148764909L, 0xa6648a214c206698L, 0x12a1d358b101f297L, "Multiplicity", "r:fbcd0e44-58df-4be0-8f6c-750fc6a4ebe5(MetaModel.structure)/1342586541813396119");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_PartialMap_0 = new EnumerationDescriptor.MemberDescriptor("PartialMap", "PartialMap", 0x12a1d358b101f298L, "r:fbcd0e44-58df-4be0-8f6c-750fc6a4ebe5(MetaModel.structure)/1342586541813396120");
  private final EnumerationDescriptor.MemberDescriptor myMember_TotalMap_0 = new EnumerationDescriptor.MemberDescriptor("TotalMap", "TotalMap", 0x12a1d358b101f299L, "r:fbcd0e44-58df-4be0-8f6c-750fc6a4ebe5(MetaModel.structure)/1342586541813396121");
  private final EnumerationDescriptor.MemberDescriptor myMember_List_0 = new EnumerationDescriptor.MemberDescriptor("List", "List", 0x5b448949fec65373L, "r:fbcd0e44-58df-4be0-8f6c-750fc6a4ebe5(MetaModel.structure)/6576532306767795059");
  private final EnumerationDescriptor.MemberDescriptor myMember_Set_0 = new EnumerationDescriptor.MemberDescriptor("Set", "Set", 0x12a1d358b101f2a0L, "r:fbcd0e44-58df-4be0-8f6c-750fc6a4ebe5(MetaModel.structure)/1342586541813396128");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9859e7a148764909L, 0xa6648a214c206698L, 0x12a1d358b101f297L, 0x12a1d358b101f298L, 0x12a1d358b101f299L, 0x5b448949fec65373L, 0x12a1d358b101f2a0L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_PartialMap_0, myMember_TotalMap_0, myMember_List_0, myMember_Set_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_TotalMap_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "PartialMap":
        return myMember_PartialMap_0;
      case "TotalMap":
        return myMember_TotalMap_0;
      case "List":
        return myMember_List_0;
      case "Set":
        return myMember_Set_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
