package MetaModel.textGen;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SProperty;

public abstract class SModelTest {
  public static void perform(SNode service, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    SNode aClass;
    aClass = SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getChildren(service, LINKS.generalisations$nqoF)).first(), LINKS.general$Kb60);
    String name = SPropertyOperations.getString(aClass, PROPS.name$tAp1);
    tgs.append(name);
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink generalisations$nqoF = MetaAdapterFactory.getContainmentLink(0x9859e7a148764909L, 0xa6648a214c206698L, 0x355f4a6bd0ef9b51L, 0x355f4a6bd0f11e99L, "generalisations");
    /*package*/ static final SReferenceLink general$Kb60 = MetaAdapterFactory.getReferenceLink(0x9859e7a148764909L, 0xa6648a214c206698L, 0x355f4a6bd0f11480L, 0x355f4a6bd0f11481L, "general");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$tAp1 = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
